### ISSUE TITLE
Dependency Vulnerability Alert

### ISSUE THREAD

**Issue by fz9** [awsug/communityday.awsug.asia#2]
@plug-n-play 
I see a security alert on the .in repo: https://github.com/awsug/communityday.awsug.in/security/dependabot/package-lock.json/lodash/open

It appears it's the same dependency on .asia repo but do not see any alerts on it. Could you check and upgrade if needed.

**Comment by plug-n-play** [comment]
@fz9 I see a 404 when I click on the link. Is this still valid?

**Comment by fz9** [comment]
@plug-n-play , same alert for awsug.asia site is showing now. Please try this link:
https://github.com/awsug/communityday.awsug.asia/security/dependabot/package-lock.json/lodash/open

**Comment by plug-n-play** [comment]
Fixed by removing package-lock.json
