### ISSUE TITLE
Name under volunteer list

### ISSUE THREAD

**Issue by piyushjalan02** [awsug/communityday.awsug.asia#3]
Can we please update my name under volunteer section ?

**Comment by fz9** [comment]
@piyushjalan02 - Sure. Please attach a photo and provide your LinkedIn or twitter id.

**Comment by piyushjalan02** [comment]
@fz9 below are requested details:

Name - Piyush Jalan
Head shot - https://ibb.co/bLs4bCV
LinkedIn Link - https://www.linkedin.com/in/piyush-jalan/

**Comment by piyushjalan02** [comment]
Hi @fz9 any update on above ?

**Comment by fz9** [comment]
@piyushjalan02 , do you you the headshot in a square format? The provided circle format is not fitting well in the square boxes on the site as there is no headroom in the pic.

**Comment by piyushjalan02** [comment]
@fz9 , Please find requested format here - https://ibb.co/RT5yVyQ

**Comment by fz9** [comment]
Done. Please check website after 10mins.
